defaults: &defaults
  crm-url: http://localhost:3000
  accounts-url: http://localhost:3001
  support-url: http://padma-support.com.ar
  overmind-url: http://localhost:3007
  mailing-url: http://localhost:3020
  fnz-url: http://localhost:3008
  attendance-url: http://localhost:3004
  
cloud9: &cloud9
  on-cloud9: true
  accounts-url: http://padma-accounts-<%= ENV['C9_USER'] %>.c9users.io
  overmind-url: http://padma-overmind-<%= ENV['C9_USER'] %>.c9users.io
  crm-url: http://padma-crm-<%= ENV['C9_USER'] %>.c9users.io
  contacts-url: http://padma-contacts-<%= ENV['C9_USER'] %>.c9users.io
  mailing-url: http://padma-mailing-<%= ENV['C9_USER'] %>.c9users.io
  attendance-url: http://padma-attendance-<%= ENV['C9_USER'] %>.c9users.io
  activity-stream-url: https://padma-activity-stream-<%= ENV['C9_USER'] %>.c9users.io/
  planning-url: ''

development:
  <<: *cloud9

test:
  <<: *defaults

production:
  <<: *defaults
  crm-url: http://crm.padm.am
  accounts-url: http://accounts.padm.am
  overmind-url: http://statistics.padm.am
  mailing-url: http://padma-mailing.herokuapp.com
  fnz-url: http://fnz.herokuapp.com
  attendance-url: http://attendance.padm.am


staging:
  <<: *defaults
  crm-url: http://padma-crm-staging.herokuapp.com
  accounts-url: http://padma-accounts-staging.herokuapp.com
  overmind-url: http://padma-overmind-staging.herokuapp.com
  mailing-url: http://padma-mailing-staging.herokuapp.com
  fnz-url: http://fnz-staging.herokuapp.com
  attendance-url: http://padma-attendance-staging.herokuapp.com
